### ISSUE TITLE
Cannot start service nginx, mount caused "not a directory" [Win10 / virtualbox]

### ISSUE THREAD

**Issue by c00** [settermjd/docker-for-local-development#3]
When cloning this repo and running it on a Windows machine (Windows 10 home / Virtual Box / Docker toolbox), Powershell will return the errror:

```
ERROR: for nginx  Cannot start service nginx: invalid header field value "oci runtime error: container_linux.go:247: sta
rting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting "/d
/www/dockertest2/docker/nginx/default.conf" to rootfs "/mnt/sda1/var/lib/docker/aufs/mnt/2bb556ad246980ee4
99d09d07b3e8fa290014cae1f723117652c796964f851c3" at "/mnt/sda1/var/lib/docker/aufs/mnt/2bb556ad246980ee499
d09d07b3e8fa290014cae1f723117652c796964f851c3/etc/nginx/conf.d/default.conf" caused "not a directory"
```

(I came to this repo through [this tutorial](http://www.masterzendframework.com/docker-development-environment/), so I am super new to Docker.) If I were to guess, I'd say it's looking to mount the file from the docker machine rather than the Windows host. But I'm not experienced enough with Docker to make any headway with it.

I'm using docker-compose 1.8.1, build 004ddae

**Comment by settermjd** [comment]
Sorry to not reply sooner. I'll see what I can do.

**Comment by eko24ive** [comment]
@settermjd I was able to run all docker containers provided with your config using [Win10 / virtualbox]
Perhaps this issue need more detail from @c00

**Comment by settermjd** [comment]
Thanks for doing that @eko24ive. @c00 can you share more details about the error that you encountered pls?

**Comment by c00** [comment]
I currently don't have the time to do any serious testing and feedback, but if other users say they didn't experience the same error then there's a good chance that it's something stupid I did. 

Feel free to close the issue. If in the future I run into the same issue, I'll be sure to add more details.

Thanks for getting back to me!

**Comment by settermjd** [comment]
Hey @c00 thanks for sharing mate. I'll close it. But feel free to re-open it if the issue persists.

**Comment by eko24ive** [comment]
@settermjd it's nice to see you've resolved all issues :3

**Comment by settermjd** [comment]
sure feels that way. You've been a legend. Thanks for all your help.
