### ISSUE TITLE
File not found.

### ISSUE THREAD

**Issue by denbatte** [settermjd/docker-for-local-development#4]
Following your tutorial on an windows 7 pc running docker.
Thank you for writing it!
I get a "File not found." message with the following output.
A index.php file is in the root of the project folder.

[NGINX]
2016/11/17 21:18:58 [error] 5#5: *7 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.99.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "192.168.99.100:8080"
192.168.99.1 - - [17/Nov/2016:21:18:58 +0000] "GET / HTTP/1.1" 404 27 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"

[PHP]
172.20.0.4 -  17/Nov/2016:21:18:58 +0000 "GET /index.php" 404

Any idea?
Thank you.

**Comment by nbas11** [comment]
@denbatte should be fixed after this is merged: https://github.com/settermjd/docker-for-local-development/pull/5

**Comment by settermjd** [comment]
@denbatte #5 was just merged. Can you try again and let me know if that fixes the issue?

**Comment by denbatte** [comment]
Will do so and keep you guys posted. Thanks for the response!

**Comment by settermjd** [comment]
I know this is a while ago, but did that change work @denbatte?

**Comment by denbatte** [comment]
Hi Matthew,

Kind of gave up on docker :-).
Maybe I should give it one more try.

Bart

Op vrijdag 17 februari 2017 heeft Matthew Setter <notifications@github.com>
het volgende geschreven:
> I know this is a while ago, but did that change work @denbatte?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/GlojPDVAfTrayfpXeJS8FpoGtwj4LEXgQbEjDIyzP7lVEagak-aQ36wbaA1h_emeahvGVfkD99ulqIxSGrv_f_kxdjmBNLJjnWa4YwzUE9RNbzbRhONe2Cgff6LniDbjzQ8DdHFdkETXU1PV2QDvxX74jOHiCA=s0-d-e1-ft#https://github.com/notifications/beacon/AAe1bC7FqVLXeB1Di6pEnBlMar5H8s7Qks5rdX9KgaJpZM4K11XK.gif
>

-- 
Met vriendelijke groeten,
Van den Brande Bart

**Comment by settermjd** [comment]
I can totally relate. But it's getting better. Am here if you need a hand.

**Comment by eko24ive** [comment]
I think this one is related to #6 
@denbatte could you pull changes and follow updated [README](https://github.com/settermjd/docker-for-local-development/blob/master/README.md) guide (commit: https://github.com/settermjd/docker-for-local-development/commit/3fd88810f249f65913fa61766718cbea79df5811) ?
