### ISSUE TITLE
Directory Index fails

### ISSUE THREAD

**Issue by caseybecking** [settermjd/docker-for-local-development#6]
`2016/12/29 18:24:16 [error] 7#7: *1 directory index of "/var/www/html/" is forbidden, client: 172.18.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:8080"`

**Comment by eko24ive** [comment]
I got something same:
```2017/02/17 10:16:41 [error] 5#5: *1 directory index of "/var/www/html/" is forbidden, client: 172.18.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:8080"```

**Comment by settermjd** [comment]
Sorry for not responding @caseybecking. I'll look at that today!

**Comment by eko24ive** [comment]
I'm looking into this SO qustions:
- http://stackoverflow.com/questions/19285355/nginx-403-error-directory-index-of-folder-is-forbidden
- http://stackoverflow.com/questions/6795350/nginx-403-forbidden-for-all-files

I'll update issue if some of that will fix it

**Comment by settermjd** [comment]
@eko24ive looking at it now.

**Comment by settermjd** [comment]
@eko24ive @caseybecking I'm suspecting that the default Nginx directory root didn't match your source files. Given that, I just merged two PRs that provide more information in the README and remove the default directory root configuration. I hope these changes help.

**Comment by eko24ive** [comment]
@settermjd ok, let me try

**Comment by eko24ive** [comment]
Ok, now I'm seeing this logs on nginx container:
```
172.18.0.1 - - [17/Feb/2017:11:24:41 +0000] "GET / HTTP/1.1" 404 27 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
2017/02/17 11:24:41 [crit] 5#5: *25 stat() "/var/www/html/" failed (116: Stale file handle), client: 172.18.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:8080"
2017/02/17 11:24:41 [crit] 5#5: *25 stat() "/var/www/html/" failed (116: Stale file handle), client: 172.18.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:8080"
2017/02/17 11:24:41 [error] 5#5: *25 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost:8080"
172.18.0.1 - - [17/Feb/2017:11:24:41 +0000] "GET / HTTP/1.1" 404 27 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
```

I guess this is realated to my config, give me some time to play around with it, I'll update you as soon as possible.

P.S.
Great README update !

**Comment by settermjd** [comment]
Thanks. Great to hear that you're making some progress. Let me know if you need further assistance.

**Comment by eko24ive** [comment]
I think I'm doing something wrong.
@settermjd could you help with this :
When I run `docker exec -it dockerforlocaldevelopment_nginx_1 ls -lahrt /var/www/html` i get:
```
ls: cannot access /var/www/html: Stale file handle
```

And if I run `docker exec -it dockerforlocaldevelopment_nginx_1 ls -lahrt /var/www/`
I get this:
```
ls: cannot access /var/www/html: Stale file handle
total 8.0K
d?????????  ? ?    ?       ?            ? html
drwxr-xr-x  3 root root 4.0K Feb 17 10:16 .
drwxr-xr-x 17 root root 4.0K Feb 17 10:16 ..
```

**Comment by eko24ive** [comment]
Ok, here is what I discovered.
Index file, obviously, must be `index.php`. The main issue for me was missing slash `/` at the end of `default.conf` for root:

This is wrong ✖️  :
`root /var/www/html/public;`

This is right ✔️ :
`root /var/www/html/public/;`

So after this I was able to get my page at http://localhost:8080/
Thank you @settermjd !

**Comment by settermjd** [comment]
Great to hear you got it sorted. Let me know if you need any further help. I'm planning to further extend the README over the weekend (time allowing).
