### ISSUE TITLE
Is Step 2 mandatory ?

### ISSUE THREAD

**Issue by omatrot** [settermjd/docker-for-local-development#7]
Do we really need to put all of the cloned files in the root of the php application ? Is there another way ? I'm looking for a way to include a php directory that is located elsewhere on my computer.

**Comment by settermjd** [comment]
Hey, @omatrot; no, you don't need to. If you don't want all the files, say _LICENSE_, and _README.md_, then add them to [a .dockerignore file](https://docs.docker.com/engine/reference/builder/#dockerignore-file). These work similarly to .gitignore files. Any file listed there will be ignored by commands such as `COPY`, `ADD`, etc. 

I'll update the linked tutorial to include this as well. Thanks for pointing it out.
